### ISSUE TITLE
[PE-D][Tester A] Incorrect Help Window screenshot in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-4/tp#132]
Screenshot of help window in user guide shows the URL to the upstream AB3 user guide instead of the product's user guide.

![image.png](https://raw.githubusercontent.com/Benjamin-Sim/ped/main/files/2766d1e8-71d4-4196-b2a9-7e18a0eef2fa.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Benjamin-Sim/ped#3

**Comment by gowribhat** [comment]
Duplicate of #133
