### ISSUE TITLE
[PE-D][Tester D] Date does not mention what numeric characters can be used for YYYY-MM-DD

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-4/tp#150]
![image.png](https://raw.githubusercontent.com/fungusta/ped/main/files/8f7fcd5f-9d72-44d7-8487-b9544dca0855.png)
By following the instruction format of YYYY-MM-DD, 0000-00-00 should be allowed but it is not

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: fungusta/ped#2

**Comment by leewaichong** [comment]
close with PR #229
