### ISSUE TITLE
[PE-D][Tester B] Name check that is too restrictive

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-4/tp#156]
Sometimes there are people who have names with special characters, such as T'challa from Black Panther. Perhaps a less restrictive name check would improve user experience
![image.png](https://raw.githubusercontent.com/JasonCP14/ped/main/files/3ccbd376-bc1a-46ce-8be0-0ccdbf12b013.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: JasonCP14/ped#10

**Comment by zzthian** [comment]
closed by https://github.com/AY2223S1-CS2103T-W12-4/tp/pull/198
