### ISSUE TITLE
[PE-D][Tester E] Exact Duplicate Tasks are not detected

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W12-4/tp#160]
Duplicate tasks are allowed, resubmit task using `UP` button
Might be team's intended behavior to allow for duplicate task? 

![image.png](https://raw.githubusercontent.com/highorbit25/ped/main/files/df95bfd6-1a0c-41f2-aaab-30bdc7b61b00.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: highorbit25/ped#7

**Comment by thamruicong** [comment]
Specify "Tasks can be duplicated" in UG -Evan

**Comment by zzthian** [comment]
closed by https://github.com/AY2223S1-CS2103T-W12-4/tp/pull/198
